name: Upload Photos to Blob

on:
  push:
    branches: [ main ]
    paths:
      - 'photos/**'

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Azure CLI
        uses: azure/setup-azure@v4
        with:
          enable-AzPSSession: false

      - name: Upload to Blob
        run: |
          az storage blob upload-batch \
            --connection-string "$AZURE_STORAGE_CONNECTION_STRING" \
            -s photos \
            -d photos
        env:
          AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
