name: Upload Photos to Blob

on:
  push:
    branches: [ main ]
    paths:
      - 'photos/**'

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: LanceMcCarthy/Action-AzureBlobUpload@v3
        name: Uploading to Azure storage blob
        with:
          connection_string: ${{secrets.AZURE_STORAGE_CONNECTION_STRING}}
          container_name: photos
          source_folder: photos/
          clean_destination_folder: true